Virtual environment detected.
  0%|          | 0/100 [00:00<?, ?trial/s, best loss=?]job exception: Unknown label type: continuous. Maybe you are trying to fit a classifier, which expects discrete classes on a regression target with continuous values.

  0%|          | 0/100 [00:00<?, ?trial/s, best loss=?]
Traceback (most recent call last):
  File "main.py", line 28, in <module>
    main()
  File "main.py", line 22, in main
    best_algo = choose_ML_algorithm(input_data, args.Results_File_Path, algos)
  File "/home/ICTDOMAIN/d18129068/dnam_biomarker_generator/src/dnam_biomarker_generator/compare_ML_models.py", line 117, in choose_ML_algorithm
    best = fmin(fn=obj_fns[algo], space=space, algo=tpe.suggest, max_evals=100, trials=trials, rstate=hyperopt_rstate) 
  File "/home/ICTDOMAIN/d18129068/dnam_biomarker_generator/dnam_biogen/lib/python3.8/site-packages/hyperopt/fmin.py", line 469, in fmin
    return trials.fmin(
  File "/home/ICTDOMAIN/d18129068/dnam_biomarker_generator/dnam_biogen/lib/python3.8/site-packages/hyperopt/base.py", line 671, in fmin
    return fmin(
  File "/home/ICTDOMAIN/d18129068/dnam_biomarker_generator/dnam_biogen/lib/python3.8/site-packages/hyperopt/fmin.py", line 509, in fmin
    rval.exhaust()
  File "/home/ICTDOMAIN/d18129068/dnam_biomarker_generator/dnam_biogen/lib/python3.8/site-packages/hyperopt/fmin.py", line 330, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.asynchronous)
  File "/home/ICTDOMAIN/d18129068/dnam_biomarker_generator/dnam_biogen/lib/python3.8/site-packages/hyperopt/fmin.py", line 286, in run
    self.serial_evaluate()
  File "/home/ICTDOMAIN/d18129068/dnam_biomarker_generator/dnam_biogen/lib/python3.8/site-packages/hyperopt/fmin.py", line 165, in serial_evaluate
    result = self.domain.evaluate(spec, ctrl)
  File "/home/ICTDOMAIN/d18129068/dnam_biomarker_generator/dnam_biogen/lib/python3.8/site-packages/hyperopt/base.py", line 894, in evaluate
    rval = self.fn(pyll_rval)
  File "/home/ICTDOMAIN/d18129068/dnam_biomarker_generator/src/dnam_biomarker_generator/compare_ML_models.py", line 55, in objective_svm
    model.fit(X_train, y_train)
  File "/home/ICTDOMAIN/d18129068/dnam_biomarker_generator/dnam_biogen/lib/python3.8/site-packages/sklearn/base.py", line 1152, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/ICTDOMAIN/d18129068/dnam_biomarker_generator/dnam_biogen/lib/python3.8/site-packages/sklearn/svm/_base.py", line 199, in fit
    y = self._validate_targets(y)
  File "/home/ICTDOMAIN/d18129068/dnam_biomarker_generator/dnam_biogen/lib/python3.8/site-packages/sklearn/svm/_base.py", line 743, in _validate_targets
    check_classification_targets(y)
  File "/home/ICTDOMAIN/d18129068/dnam_biomarker_generator/dnam_biogen/lib/python3.8/site-packages/sklearn/utils/multiclass.py", line 216, in check_classification_targets
    raise ValueError(
ValueError: Unknown label type: continuous. Maybe you are trying to fit a classifier, which expects discrete classes on a regression target with continuous values.
